
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'SYMBOL COUNT\n    chemical_equation :\n    chemical_equation : species_list\n    species_list :  species_list speciesspecies_list : species\n    species : SYMBOL\n    species : SYMBOL COUNT\n    '
    
_lr_action_items = {'SYMBOL':([0,1,3,4,5,6,],[1,-5,-4,1,-6,-3,]),'COUNT':([1,],[5,]),'$end':([0,1,2,3,4,5,6,],[-1,-5,0,-4,-2,-6,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'chemical_equation':([0,],[2,]),'species':([0,4,],[3,6,]),'species_list':([0,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> chemical_equation","S'",1,None,None,None),
  ('chemical_equation -> <empty>','chemical_equation',0,'p_chemical_equation','final.py',42),
  ('chemical_equation -> species_list','chemical_equation',1,'p_chemical_equation','final.py',43),
  ('species_list -> species_list species','species_list',2,'p_species_list','final.py',52),
  ('species_list -> species','species_list',1,'p_species','final.py',56),
  ('species -> SYMBOL','species',1,'p_single_species','final.py',61),
  ('species -> SYMBOL COUNT','species',2,'p_single_species','final.py',62),
]
